on:
  push:
    paths:
    - 'docusite/**'
  workflow_dispatch:

jobs:
  buildAndPublishDocusite:
    name: Build and publish docusite
    runs-on: ubuntu-latest
    steps:
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.0.2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16.1'
    - uses: actions/checkout@master
    - name: Build
      # run: |
      #   bash build.sh wasm && bash build.sh docusite
      run: bash build.sh wasm && bash build.sh docusite && bash build.sh corsproxy
    - name: Deploy production to Netlify
      uses: lsnow99/actions-netlify@v1.2.4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: "Deploy from GitHub Actions"
        publish-dir: './docusite/docs/.vuepress/dist'
        functions-dir: './dist/functions'
        enable-commit-comment: true
        production-branch: master
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
