on:
  push:
    paths:
      - "docusite/**"
  workflow_dispatch:

jobs:
  buildAndPublishDocusite:
    name: Build and publish docusite
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.16.1"
      - uses: actions/checkout@master
      - name: Build
        # run: |
        #   bash build.sh wasm && bash build.sh docusite
        run: |
          bash build.sh wasm && \
          bash build.sh docusite && \
          bash build.sh corsproxy && \
          pnpm i -g netlify-cli && \
          netlify deploy --prod \
            -a ${{ secrets.NETLIFY_AUTH_TOKEN }} \
            -s ${{ secrets.NETLIFY_SITE_ID }} \
            -f ./dist/functions \
            -d ./docusite/docs/.vuepress/dist \
            -m "Deploy from GitHub Actions"
