on:
  push:
    branches:
    - master
  workflow_dispatch:

name: Publish docusite
jobs:
  buildAndPublishDocusite:
    name: Build and publish docusite
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
        run: |
          bash build.sh wasm && bash build.sh docusite
    - name: Deploy production to Netlify
      uses: South-Paw/action-netlify-deploy@v1.2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
        build-dir: './docusite/docs/.vuepress/dist'
        comment-on-commit: true
