on:
  push:
    paths:
      - "docusite/**"
      - "cmd/csl/**"
      - "cmd/cslwasm/**"
      - "cmd/corsproxy/**"
      - "shared/**"
  workflow_dispatch:

jobs:
  buildAndPublishDocusite:
    name: Build and publish docusite
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.16.1"
      - uses: extractions/setup-just@v1
        with:
          just-version: 0.8
      - uses: actions/checkout@master
      - name: Build
        run: |
          just build-docusite
          just build-corsproxy
          pnpm i -g netlify-cli && \
          netlify deploy --prod \
            -a ${{ secrets.NETLIFY_AUTH_TOKEN }} \
            -s ${{ secrets.NETLIFY_SITE_ID }} \
            -f ./dist/functions \
            -d ./docusite/docs/.vitepress/dist \
            -m "Deploy from GitHub Actions"
